module.exports = {
	reactions: {
		'W82S43': [RESOURCE_HYDROGEN, RESOURCE_OXYGEN],
		'W83S43': [RESOURCE_HYDROGEN, RESOURCE_UTRIUM],
		'W85S41': [RESOURCE_UTRIUM_ACID, RESOURCE_CATALYST],
		'W88S41': [RESOURCE_UTRIUM_HYDRIDE, RESOURCE_HYDROXIDE],
	},
	terminalSends: {
		'W82S43': {
			'W85S41': [RESOURCE_UTRIUM_ACID],
			'W88S41': [RESOURCE_HYDROXIDE],
		},
		'W83S43': {
			'W82S43': [RESOURCE_OXYGEN],
			'W88S41': [RESOURCE_UTRIUM_HYDRIDE, RESOURCE_HYDROXIDE],
		},
		'W88S41': {
			'W82S43': [RESOURCE_OXYGEN],
			'W85S41': [RESOURCE_UTRIUM_ACID],
		},
		'W88S36': {
		    'W83S43': [RESOURCE_HYDROGEN]
		}
	},
}